[Half] Pro ability of downloading from launchpad.net

diff --git a/download b/download
--- a/download
+++ b/download
@@ -12,13 +12,18 @@ if [ ! -d "srcs" ];  then
     mkdir srcs
 fi
 
-SOURCE="https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc"
-# SOURCE="https://launchpad.net/ubuntu/+source/glibc/2.31-0ubuntu9.1/+build/19905528/+files"
-# Use the source below if you feel slow, or change it on your own.
 # SOURCE="http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/"
+SOURCE="https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc"
+SRC_SROUCE=$SOURCE
+
+# SOURCE="https://launchpad.net/~ubuntu-security-proposed/+archive/ubuntu/ppa/+build/14236598/+files"
+# SRC_SOURCE="https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/glibc/2.26-0ubuntu2.1"
+# Use the source below if you feel slow, or change it on your own.
 
 LIBC_PREFIX="libc6_"
 LIBC_DBG_PREFIX="libc6-dbg_"
+GLIBC_SOURCE_PREFIX="glibc-source_"
+GLIBC_SOURCE_SUFFIX="_all"
 
 die() {
   echo >&2 $1
@@ -36,6 +41,8 @@ download_single() {
   local dbg_name=$LIBC_DBG_PREFIX$id.deb
   local glibc_ver=${id%%-*}
   local src_name="glibc_${glibc_ver}.orig.tar.xz"
+  # local glibc_ver=${id%_*}
+  # local src_name=$GLIBC_SOURCE_PREFIX$glibc_ver$GLIBC_SOURCE_SUFFIX.deb
   echo "========== Dowloading $id =========="
   if [ -d "libs/$id" ]; then
     die "  --> Downloaded before. Remove it to download again."
@@ -45,17 +52,20 @@ download_single() {
   local url="$SOURCE/$deb_name"
   echo "  -> Location: $url"
   echo "  -> Downloading libc binary package"
-  wget "$url" 2>/dev/null -O debs/$deb_name || die "Failed to download package from $url"
+  if [ ! -f debs/$deb_name ]; then
+    wget "$url" 2>/dev/null -O debs/$deb_name || die "Failed to download package from $url"
+  fi
 
   # download debug info package
   local url="$SOURCE/$dbg_name"
   echo "  -> Location: $url"
   echo "  -> Downloading libc debug package"
-  wget "$url" 2>/dev/null -O debs/$dbg_name || die "Failed to download package from $url"
-
+  if [ ! -f debs/$dbg_name ]; then
+    wget "$url" 2>/dev/null -O debs/$dbg_name || die "Failed to download package from $url"
+  fi
   # download source package
   if [ ! -f "srcs/$src_name" ]; then
-    local url="$SOURCE/$src_name"
+    local url="$SRC_SOURCE/$src_name"
     echo "  -> Location: $url"
     echo "  -> Downloading libc source package"
     wget "$url" 2>/dev/null -O srcs/$src_name || die "Failed to download package from $url"
